export const skyBetNextRacesHorse = "https://m.skybet.com/horse-racing"
export const frontendDevDomain = "http://localhost:5173"
export const frontendDevPreviewProdDomain = "http://localhost:4173"
export const frontendProdDomain = "https://frontend.kennethman.com"
export const sharedRootDomainName = ".kennethman.com"